In [3]:
import numpy as np
from scipy.stats import multivariate_normal

Log:

- 11/10 Fixed bugs: H^(-1/2) formula, shapes of theta & epsilons

# Functions to be tested

For now, use a very simple function - quadratic with max value 0, and theta* = [0.5, 0.5] 

Also note that we will maximize the function, not minimize.

In [4]:
def F(theta):
    return -sum((theta - 0.5) ** 2)

# Gradient benchmark

This is exactly the Algorithm 1 in the RL paper.

In [3]:
def ES_benchmark_gradient(alpha, sigma, theta_0, num_samples, time_steps):
    theta_t = theta_0
    d = theta_0.shape[0]
    n = num_samples
    for t in range(time_steps):
        #**** sample epsilons ****#
        eps_list = [] 
        for i in range(n):
            eps = np.random.multivariate_normal(mean = np.zeros(d), cov = np.identity(d))
            eps_list.append(eps)
        #**** compute function values ****#
        F_list = []
        for i in range(n):
            F_val = F(theta_t + sigma*eps_list[i])
            F_list.append(F_val)
        #**** update theta ****#
        new_theta = theta_t
        for i in range(n):
            new_theta += alpha / (n*sigma) * F_list[i] * eps_list[i]
        theta_t = new_theta
    return theta_t, F(theta_t)

In [4]:
#ES_benchmark_gradient(alpha=0.0005, sigma=0.01, theta_0 = np.array([1.0,1.0]), num_samples = 50, time_steps = 10000)

# HessAware Benchmark

This implements the Hess Aware algorithm in Zhang's paper. 

The Hessian estimate comes from Section 4.1.

In [48]:
def ES_benchmark_hess_aware(alpha, sigma, theta_0, num_samples, time_steps, p, H_lambda):
    d = theta_0.shape[0]
    theta_t = theta_0.reshape((d,1))
    n = num_samples
    H = None
    for t in range(time_steps):
        #**** sample epsilons ****#
        eps_list = [] 
        for i in range(n):
            eps = np.random.multivariate_normal(mean = np.zeros(d), cov = np.identity(d))
            eps_list.append(eps.reshape(d,1))
        #**** compute function values ****#
        F_plus_list = []
        F_minus_list = []
        F_list = []
        for i in range(n):
            F_plus_list.append(F(theta_t + sigma*eps_list[i]))
            F_minus_list.append(F(theta_t - sigma*eps_list[i]))
            F_list.append(F(theta_t))
        #**** compute Hessian every p steps ****#
        if t % p == 0:
            H = np.zeros((d,d))
            for i in range(n):
                e_i = eps_list[i]
                e_i_trans = np.transpose(eps_list[i])
                H += (F_plus_list[i] + F_minus_list[i] - 2*F_list[i]) * (e_i @ e_i_trans)
            H /= 2*(sigma**2)*n
            H += H_lambda * np.identity(d)
        #**** update theta: compute g ****#
        u, s, vh = np.linalg.svd(H)
        H_nh = u @ np.diag(s**-0.5) @ vh
        g = 0
        for i in range(n):
            e_i = eps_list[i]
            F_new = F(theta_t +  sigma* (H_nh @ e_i)  )
            g += ((F_new - F(theta_t)) / sigma ) * (H_nh @ e_i) / n
        #**** update theta: the rest ****#
        new_theta = theta_t + alpha * g
        theta_t = new_theta
        
    return theta_t, F(theta_t), H

In [49]:
ES_benchmark_hess_aware(alpha=0.1, sigma=0.01, theta_0=np.array([1.0,1.0]), num_samples = 50, time_steps = 100, p = 10, H_lambda = 0)

(array([[0.50333775],
        [0.50043981]]),
 array([-1.13340368e-05]),
 array([[-7.41151043,  0.96900837],
        [ 0.96900837, -3.3032112 ]]))

# First Hessian-based method

We use the Hessian estimate as in the write-up document on Overleaf.

Then, the same Newton's method as in Zhang's paper is used to update theta with the Hessian estimate.

As before, alpha is the learning rate. The parameter p defines how often we re-compute the Hessian.

In [50]:
def ES_hessian(alpha, sigma, theta_0, num_samples, time_steps, p, H_lambda):
    d = theta_0.shape[0]
    theta_t = theta_0.reshape((d,1))
    n = num_samples
    H = None
    for t in range(time_steps):
        #**** sample epsilons ****#
        eps_list = [] 
        for i in range(n):
            eps = np.random.multivariate_normal(mean = np.zeros(d), cov = np.identity(d))
            eps_list.append(eps.reshape(d,1))
        #**** compute function values ****#
        F_list = []
        for i in range(n):
            F_val = F(theta_t + sigma*eps_list[i])
            F_list.append(F_val)
        #**** compute Hessian every p steps ****#
        if t % p == 0:
            H = np.zeros((d,d))
            for i in range(n):
                e_i = eps_list[i].reshape((d,1))
                e_i_trans = np.transpose(e_i)
                H += F_list[i] * (e_i @ e_i_trans - np.identity(d)) 
            H /= (sigma**2) * n
            H += H_lambda * np.identity(d)
        #**** update theta: compute g ****#
        u, s, vh = np.linalg.svd(H)
        H_nh = u @ np.diag(s**-0.5) @ vh
        g = 0
        for i in range(n):
            e_i = eps_list[i]
            F_new = F(theta_t +  sigma* (H_nh @ e_i)  )
            g += ((F_new - F(theta_t)) / sigma ) * (H_nh @ e_i) / n
        #**** update theta: the rest ****#
        new_theta = theta_t + alpha * g
        theta_t = new_theta
        
    return theta_t, F(theta_t), H

In [51]:
ES_hessian(alpha=0.1, sigma=0.01, theta_0=np.array([1.0,1.0]), num_samples = 50, time_steps = 1000, p = 10, H_lambda = 1e-4)

(array([[0.59805139],
        [0.64286997]]),
 array([-0.0300259]),
 array([[19.44603507, -7.57739728],
        [-7.57739728, 39.47890787]]))